name: API-Rex API Documentation Action
description: Keep your API-Rex API Documentation updated
inputs:
  FILE_PATH:
    description: "File path to API Spec File"
    required: true
  SECRET_API_KEY:
    description: "API Key from API-Rex website"
    required: true
  PROJECT_UID:
    description: "Project UID from API-Rex website"
    required: true
  IMPORT_METHOD:
    description: "Import method"
    required: false
    default: "overwrite" # options include: overwrite, merge
  AUTO_PUBLISH:
    description: "Auto publish documentation"
    required: false
    default: "false"
  API_BASE_URL:
    description: "API Base URL"
    required: false

runs:
  using: "node16"
  main: "src/index.js"
branding:
  icon: "book-open"
  color: "green"
