name: Update Documentation
on:
  push:
    branches:
      - main
jobs:
  update-doc:
    name: Update API-Rex Documentation
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - name: Update documentation on server
        uses: API-Rex/api-rex-action@main
        with:
          FILE_PATH: test/openapi_example.yaml
          SECRET_API_KEY: ${{secrets.API_REX_ACCOUNT_SECRET}}
          PROJECT_UID: ${{vars.PROJECT_UID}}
          IMPORT_METHOD: overwrite
          AUTO_PUBLISH: true
          API_BASE_URL: ${{vars.API_BASE_URL}}
